# Site settings
title: Ewan S. Douglas
tag_text: Ewan S. Douglas
description: An astronomer specializing in building instruments with a particular focus on direct imaging of exoplanets - worlds around other stars
url: "http://127.0.0.1:4000"
baseurl: ""
twitter_username:     e_douglas
github_username:      douglase
linkedin_username:    Ewan-s-douglas-31317034
gscholar_username: 	mwPSu8AAAAJ
font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
