# Site settings
title: Ewan Douglas
tag_text: Ewan Douglas
description:
url: "http://127.0.0.1:4000"
baseurl: ""
twitter_username:     douglase
github_username:      douglase
linkedin_username:    https://www.linkedin.com/in/ewan-s-douglas-31317034/
gscholar_username: 	mwPSu8AAAAJ
font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
