# Site settings
title: Ewan Douglas
tag_text: Ewan Douglas
description: "astronomer building space telescopes large and small, with a focus on directly imaging  exoplanets -- worlds around other stars"
url: "http://127.0.0.1:4000"
baseurl: ""
twitter_username:     e_douglas
github_username:      douglase
linkedin_username:    Ewan-s-douglas-31317034
gscholar_username: 	mwPSu8AAAAJ
ads_custom_search:  "https://ui.adsabs.harvard.edu/#search/q=orcid%3A0000-0002-0813-4308&sort=date%20desc%2C%20bibcode%20desc"
contact_page: "https://www.as.arizona.edu/people/faculty/ewan-douglas"
font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
